#!/bin/bash

# do *not* specify -o pipefail, due to "| grep -q" below
set -meu
IFS=

usage() {
    echo "Usage: $0 make-targets..."
    echo "  Runs the given make targets in parallel but with separated outputs"
    exit 1
}

if [ $# -eq 0 ] || [ "$1" = -h ] || [ "$1" = --help ]; then
   usage
fi

targets=("$@")

run() {
    local target=$1
    echo "+ make $target"
    if time make "$target"; then
        echo -e "\n$target: Ok."
    else
        echo -e "\n$target: Err: $?"
    fi
}

tmpdir=$(mktemp -d)
# Leak the files in tmpdir on purpose so that they can be examined.
echo "ci-make writing to $tmpdir"

i=0
for target in "${targets[@]}"; do
    tmp="$tmpdir/$i"
    i=$(( i + 1 ))
    ( run "$target" 2>&1 | test/target/debug/log-timestamp > "$tmp" ) &
done

for _target in "${targets[@]}"; do
    wait || true
done

exit_code=0

i=0
for _target in "${targets[@]}"; do
    tmp="$tmpdir/$i"
    i=$(( i + 1 ))
    echo "========================================================================================"
    if tail -1 "$tmp" | grep -q ": Ok."; then
        if [ "${CI_MAKE_VERBOSE-}" == 1 ]; then
            cat "$tmp"
        else
            tail -1 "$tmp"
        fi
    else
        exit_code=$((exit_code + 1))
        cat "$tmp"
    fi
done

echo "========================================================================================"

exit "$exit_code"
