[package]
name = "split-patch"
version = "0.1.0"
edition = "2021"
description = "Split patch files on file, hunk or change boundaries"
repository = "https://github.com/IntermediateResults/split-patch"

[dependencies]
patchparser = { path = "patchparser" }

anyhow = { version = "1.0", features = ["backtrace"] }
bstr = { version = "1.10", default-features = false, features = ["alloc"] }
bumpalo = { version = "3.19.1", features = ["collections"] }
cj-path-util = { version = "0.4.0", features = ["unix"] }
clap = { version = "4", features = ["derive"] }
clap-with-warnings = { version = "0.1.4" }
derive_more = { version = "2.0.1", features = ["from", "from_str"] }
lazy_static = "1.4"
mockalloc = { git = "https://github.com/diggsey/mockalloc", rev = "103439477d7e6acccef3c203730ed3009f3dec41" }
rayon = "1.10.0"
regex = "1.4.6"
