[package]
name = "split-patch"
version = "0.1.0"
edition = "2021"
description = "Split patch files on file, hunk or change boundaries"
repository = "https://github.com/IntermediateResults/split-patch"

[lints.clippy]
# Naming lifetimes can be explanatory; even if it's not really, we
# generally prioritize moving on with the project.
needless_lifetimes = "allow"
# Nesting if statements can be clearer
collapsible_else_if = "allow"
collapsible_if = "allow"
# Having to write "x" as 'x' while another branch uses "yz" is
# silly. It might even be less efficient.
single_char_add_str = "allow"
# We should inherently strive for simple types anyway. Having to
# explicitly allow the cases that are not easy to simplify seems
# wasteful on our time. (We may run clippy with `-W clippy::all` from
# time to time.)
type_complexity = "allow"

[[bin]]
name = "test-split-patches-in-dir"
path = "test/test-split-patches-in-dir.rs"

[dependencies]
patchparser = { path = "../patchparser" }

anstyle = "1.0.7"
anyhow = { version = "1.0", features = ["backtrace"] }
bstr = { version = "1.10", default-features = false, features = ["alloc"] }
bumpalo = { version = "3.19.1", features = ["collections"] }
cj-path-util = { version = "0.4.0", features = ["unix"] }
clap = { version = "4", features = ["derive", "wrap_help"] }
clap-with-warnings = { version = "0.1.4" }
derive_more = { version = "2.0.1", features = ["from", "from_str"] }
lazy_static = "1.4"
rayon = "1.10.0"
regex = "1.4.6"
